# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  version: "1.2.3"
  application_name: "my-api-provider"
  PACT_BROKER_BASE_URL: https://galwayse.pactflow.io
  PACT_BROKER_TOKEN: 9rHjtK3ssQ-kXAC2qAZW9A

jobs:
  pact-publish-oas-action:
    runs-on: ubuntu-latest
    steps:
      # MANDATORY: Must use 'checkout' first
      - uses: actions/checkout@v2
      - name: Publish provider contract 
      - uses: pactflow/actions/publish-provider-contract@v1.0.1
        env:
          oas_file: src/api-docs.yml
          results_file: src/results/report.md
          EXIT_CODE: 1
